[Greeter]
background=/usr/share/backgrounds/wallpaper.png
draw-user-backgrounds=false
draw-grid=false
theme-name=Arc-Dark
icon-theme-name=Qogir-Dark
cursor-theme-name=Qogir-Dark
cursor-theme-size=24
show-a11y=false
show-power=true
background-color=#000000
