# Prefix → Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Mouse
set -g mouse on

# Índice desde 1
set -g base-index 1
set -g pane-base-index 1

# Colores
set -g default-terminal "screen-256color"

# Splits intuitivos
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Navegación entre paneles con Alt+flechas
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Recargar config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config recargada"

# Barra de estado
set -g status-position bottom
set -g status-bg "#1E1E2E"
set -g status-fg "#CDD6F4"
set -g status-left "#[fg=#c94a1a,bold] #S "
set -g status-right "#[fg=#89B4FA] %d/%m/%Y #[fg=#c94a1a] %H:%M "
set -g window-status-current-format "#[fg=#c94a1a,bold] #I:#W "
set -g window-status-format "#[fg=#CDD6F4] #I:#W "

# Plugin manager TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Auto-guardar sesiones
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
